# Generated by Django 3.1.3 on 2020-11-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20201119_2152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
